databaseGenerator:
  url: jdbc:mysql://localhost:3306/data
  userName: root
  password: root
  author: kaki
  tables: user,orders
  packageConfig:
    javaTargetProject: /Users/kaki/IdeaProjects/carbon-mybatis-generator/carbon-mybatis-generator-plugin/src/test/java/com/carbon
    xmlTargetProject: /Users/kaki/IdeaProjects/carbon-mybatis-generator/carbon-mybatis-generator-plugin/src/test/java/resources/mapper